### ISSUE TITLE
Device not found using ESP32 + Wokwi

### ISSUE THREAD

**Issue by knightpp** [kelnos/dht-embedded-rs#4]
Hi. I use Wokwi emulator, you can try the test project here https://wokwi.com/projects/368352408492370945.

I adapted your example from README.md to ESP32 hal, but the log says `Error: DHT device not found`. Do you know what I am doing wrong?

**Comment by koenw** [comment]
I can confirm this issue also exists using hardware.

**Comment by knightpp** [comment]
I've not tried but the possible solution is https://github.com/michaelbeaumont/dht-sensor/issues/23#issuecomment-1784107501

**Comment by kelnos** [comment]
Ah interesting.  I'd always used open drain but hadn't known it was required.

I tried modifying the Wokwi project, but cloning some fork of this repo failed.  Tried to use the main version, but that didn't work for other reasons, and I don't really have the time to learn how Wokwi works right now.  @knightpp, can you get your project working again and give it a try?

**Comment by navaati** [comment]
Hi !

Ah, funny how things happen, just at this instant I found that solution as well on my side (on actual hardware). So, I confirm it works with `input_output_od`. Too bad the types in embedded_hal don’t prevent that…

**Comment by kelnos** [comment]
Ok, it took some doing, but I managed to get it working on Wokwi, using the latest versions of things as well as using the open-drain pin.  Temp and humidity print out as 0 tho, I assume that's just what the simulator does... I hope.

**Comment by SergioGasquez** [comment]
For reference, here is a working Wokwi project with DHT22: https://wokwi.com/projects/384087992261474305
